## send post action
DELETE    http://localhost:4004/v2/services/compliance/TiposAlerta(ID='fa81611-1e2b-4c86-b3b3-cf73b12fe675')
Authorization: Basic P0646683:1234
Content-Type: application/json

//{"ids":"6fa81611-1e2b-4c86-b3b3-cf73b12fe675;"}